language: go

go:
  - 1.2
  - tip

install:
  - go get -v -t ./...
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go get -v github.com/mattn/goveralls

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - go test -v ./...
  - ./test-coverage.sh
  - goveralls -v -coverprofile=acc.out -service=travis-ci
